main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: research/
    weight: 20
  - name: Publications
    url: publications/
    weight: 30
  - name: Talks
    url: events/
    weight: 40
  - name: Teaching
    url: teaching/
    weight: 50
  - name: Blog
    url: blog/
    weight: 60
  - name: CV
    url: uploads/sean-ma-cv.pdf
    weight: 70
